services:
  # Service principal - Arsenal Bot + WebPanel intégré
  - type: web
    name: arsenal-webpanel
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python webpanel_advanced.py --start-bot --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.18
      - key: DISCORD_TOKEN
        sync: false
      - key: BOT_PREFIX
        value: "!"
      - key: WEB_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: FLASK_ENV
        value: production
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: ARSENAL_MODE
        value: production
      - key: WEB_AUTH_ENABLED
        value: true
      - key: MAX_LOG_LINES
        value: 1000
      - key: AUTO_RESTART
        value: true
        sync: false
      - key: DISCORD_REDIRECT_URI
        value: https://arsenal-webpanel.onrender.com/auth/callback
